-- Oracle 19c schema supplement for the student course selection system.
-- Run this file with the application schema user before using the full admin module.

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE role (
            role_id NUMBER(1) PRIMARY KEY,
            role_name VARCHAR2(20) NOT NULL UNIQUE,
            role_desc VARCHAR2(255)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE "user" (
            user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            username VARCHAR2(20) NOT NULL UNIQUE,
            password VARCHAR2(32) NOT NULL CHECK (LENGTH(password) = 32),
            role_id NUMBER(1) NOT NULL REFERENCES role(role_id),
            real_name VARCHAR2(50) NOT NULL,
            phone VARCHAR2(11),
            email VARCHAR2(50),
            status NUMBER(1) DEFAULT 1 NOT NULL CHECK (status IN (0, 1)),
            last_login DATE,
            create_time DATE DEFAULT SYSDATE NOT NULL,
            CONSTRAINT ck_user_phone CHECK (phone IS NULL OR LENGTH(phone) = 11),
            CONSTRAINT ck_user_email CHECK (email IS NULL OR INSTR(email, '@') > 1),
            CONSTRAINT ck_user_last_login CHECK (last_login IS NULL OR last_login >= create_time)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE student (
            user_id NUMBER PRIMARY KEY REFERENCES "user"(user_id),
            student_no VARCHAR2(20) NOT NULL UNIQUE,
            major VARCHAR2(50) NOT NULL,
            grade VARCHAR2(10) NOT NULL,
            avg_gpa NUMBER(3,2) DEFAULT 0 NOT NULL CHECK (avg_gpa BETWEEN 0 AND 5),
            credit_finished NUMBER(5,1) DEFAULT 0
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE teacher (
            user_id NUMBER PRIMARY KEY REFERENCES "user"(user_id),
            teacher_no VARCHAR2(20) NOT NULL UNIQUE,
            title VARCHAR2(20) NOT NULL,
            department VARCHAR2(50) NOT NULL
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE administrator (
            user_id NUMBER PRIMARY KEY REFERENCES "user"(user_id),
            admin_no VARCHAR2(20) NOT NULL UNIQUE,
            admin_level NUMBER(1) NOT NULL CHECK (admin_level IN (0, 1)),
            managed_scope CLOB
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE permission (
            perm_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            perm_code VARCHAR2(50) NOT NULL UNIQUE,
            perm_name VARCHAR2(50) NOT NULL,
            module VARCHAR2(50) NOT NULL
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE role_permission (
            role_id NUMBER(1) NOT NULL REFERENCES role(role_id),
            perm_id NUMBER NOT NULL REFERENCES permission(perm_id),
            CONSTRAINT pk_role_permission PRIMARY KEY (role_id, perm_id)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE course (
            course_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            course_name VARCHAR2(20) NOT NULL,
            course_type VARCHAR2(20) NOT NULL,
            credit NUMBER(3,1) NOT NULL CHECK (credit >= 0),
            total_hours NUMBER NOT NULL CHECK (total_hours >= 0),
            department VARCHAR2(100),
            course_desc VARCHAR2(1000)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE section (
            section_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            course_id NUMBER NOT NULL REFERENCES course(course_id),
            semester VARCHAR2(20) NOT NULL
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE teaching_class (
            class_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            class_name VARCHAR2(50) NOT NULL,
            teacher_no VARCHAR2(20) NOT NULL REFERENCES teacher(teacher_no),
            capacity NUMBER NOT NULL CHECK (capacity >= 0),
            selected_count NUMBER DEFAULT 0 NOT NULL CHECK (selected_count >= 0),
            section_id NUMBER NOT NULL REFERENCES section(section_id),
            CONSTRAINT ck_teaching_capacity CHECK (selected_count <= capacity)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE course_time (
            time_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            class_id NUMBER NOT NULL REFERENCES teaching_class(class_id),
            weekday NUMBER NOT NULL CHECK (weekday BETWEEN 1 AND 7),
            start_period NUMBER NOT NULL CHECK (start_period BETWEEN 1 AND 10),
            end_period NUMBER NOT NULL CHECK (end_period BETWEEN 1 AND 10),
            week_range VARCHAR2(50) NOT NULL,
            classroom VARCHAR2(50) NOT NULL,
            CONSTRAINT ck_course_time_period CHECK (start_period <= end_period)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE selection_batch (
            batch_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            batch_name VARCHAR2(50) NOT NULL,
            start_time DATE NOT NULL,
            end_time DATE NOT NULL,
            status NUMBER(1) NOT NULL CHECK (status IN (0, 1, 2)),
            CONSTRAINT ck_selection_batch_time CHECK (start_time < end_time)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE course_select (
            select_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            class_id NUMBER NOT NULL REFERENCES teaching_class(class_id),
            batch_id NUMBER NOT NULL REFERENCES selection_batch(batch_id),
            student_no VARCHAR2(20) NOT NULL REFERENCES student(student_no),
            select_time DATE DEFAULT SYSDATE NOT NULL,
            CONSTRAINT uq_course_select UNIQUE (class_id, student_no)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE student_score (
            score_id VARCHAR2(40) PRIMARY KEY,
            student_no VARCHAR2(20) NOT NULL REFERENCES student(student_no),
            class_id NUMBER NOT NULL REFERENCES teaching_class(class_id),
            total_score NUMBER(5,1) CHECK (total_score BETWEEN 0 AND 100),
            grade_level VARCHAR2(10),
            gpa NUMBER(3,2),
            credit_obtained NUMBER(3,1) DEFAULT 0 NOT NULL,
            entry_time DATE DEFAULT SYSDATE,
            update_remark VARCHAR2(200),
            update_time DATE,
            CONSTRAINT uq_student_score UNIQUE (student_no, class_id)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE course_evaluation (
            eval_id VARCHAR2(40) PRIMARY KEY,
            student_no VARCHAR2(20) NOT NULL REFERENCES student(student_no),
            class_id NUMBER NOT NULL REFERENCES teaching_class(class_id),
            d1_score NUMBER(1) NOT NULL CHECK (d1_score BETWEEN 1 AND 5),
            d2_score NUMBER(1) NOT NULL CHECK (d2_score BETWEEN 1 AND 5),
            d3_score NUMBER(1) NOT NULL CHECK (d3_score BETWEEN 1 AND 5),
            d4_score NUMBER(1) NOT NULL CHECK (d4_score BETWEEN 1 AND 5),
            eval_score NUMBER(3,1) NOT NULL,
            eval_content CLOB,
            eval_time DATE DEFAULT SYSDATE NOT NULL,
            CONSTRAINT uq_course_evaluation UNIQUE (student_no, class_id)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE system_log (
            log_id VARCHAR2(40) PRIMARY KEY,
            user_id NUMBER REFERENCES "user"(user_id),
            operation_type VARCHAR2(30) NOT NULL,
            operation_desc VARCHAR2(255),
            target_id VARCHAR2(40),
            ip_address VARCHAR2(45),
            request_params CLOB,
            result_status VARCHAR2(20) NOT NULL,
            error_msg VARCHAR2(255),
            log_time DATE DEFAULT SYSDATE NOT NULL
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE course_application (
            apply_id VARCHAR2(40) PRIMARY KEY,
            teacher_no VARCHAR2(20) NOT NULL REFERENCES teacher(teacher_no),
            course_name VARCHAR2(100) NOT NULL,
            course_type VARCHAR2(20),
            credit NUMBER(3,1) NOT NULL,
            total_hours NUMBER NOT NULL,
            department VARCHAR2(100),
            course_summary VARCHAR2(4000),
            teaching_plan CLOB,
            description CLOB,
            target_major VARCHAR2(50),
            target_grade VARCHAR2(10),
            textbook VARCHAR2(200),
            apply_time DATE DEFAULT SYSDATE NOT NULL,
            status VARCHAR2(20) DEFAULT '待审核' NOT NULL,
            approve_time DATE,
            approve_comment VARCHAR2(255),
            review_remark VARCHAR2(255)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

DECLARE
    PROCEDURE add_column_if_missing(p_table VARCHAR2, p_column VARCHAR2, p_sql VARCHAR2) IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
          INTO v_count
          FROM user_tab_columns
         WHERE table_name = UPPER(p_table)
           AND column_name = UPPER(p_column);

        IF v_count = 0 THEN
            EXECUTE IMMEDIATE p_sql;
        END IF;
    END;
BEGIN
    add_column_if_missing('course_application', 'course_type', 'ALTER TABLE course_application ADD (course_type VARCHAR2(20))');
    add_column_if_missing('course_application', 'department', 'ALTER TABLE course_application ADD (department VARCHAR2(100))');
    add_column_if_missing('course_application', 'course_summary', 'ALTER TABLE course_application ADD (course_summary VARCHAR2(4000))');
    add_column_if_missing('course_application', 'description', 'ALTER TABLE course_application ADD (description CLOB)');
    add_column_if_missing('course_application', 'target_major', 'ALTER TABLE course_application ADD (target_major VARCHAR2(50))');
    add_column_if_missing('course_application', 'target_grade', 'ALTER TABLE course_application ADD (target_grade VARCHAR2(10))');
    add_column_if_missing('course_application', 'review_remark', 'ALTER TABLE course_application ADD (review_remark VARCHAR2(255))');
END;
/

CREATE OR REPLACE TRIGGER trg_course_app_summary
BEFORE INSERT OR UPDATE ON course_application
FOR EACH ROW
BEGIN
    IF :NEW.course_summary IS NULL THEN
        IF :NEW.description IS NOT NULL THEN
            :NEW.course_summary := DBMS_LOB.SUBSTR(:NEW.description, 4000, 1);
        ELSIF :NEW.teaching_plan IS NOT NULL THEN
            :NEW.course_summary := DBMS_LOB.SUBSTR(:NEW.teaching_plan, 4000, 1);
        END IF;
    END IF;
END;
/

MERGE INTO role r
USING (
    SELECT 0 AS role_id, 'student' AS role_name, '学生' AS role_desc FROM dual UNION ALL
    SELECT 1, 'teacher', '教师' FROM dual UNION ALL
    SELECT 2, 'admin', '管理员' FROM dual
) src
ON (r.role_id = src.role_id)
WHEN NOT MATCHED THEN
    INSERT (role_id, role_name, role_desc)
    VALUES (src.role_id, src.role_name, src.role_desc);

MERGE INTO permission p
USING (
    SELECT 1 AS perm_id, 'admin:login' AS perm_code, '管理员登录' AS perm_name, 'backend' AS module FROM dual UNION ALL
    SELECT 2, 'course:manage', '课程管理', 'backend' FROM dual UNION ALL
    SELECT 3, 'application:review', '开课申请审批', 'backend' FROM dual UNION ALL
    SELECT 4, 'student:manage', '学生信息管理', 'backend' FROM dual UNION ALL
    SELECT 5, 'teacher:manage', '教师信息管理', 'backend' FROM dual UNION ALL
    SELECT 6, 'batch:manage', '选课批次管理', 'backend' FROM dual UNION ALL
    SELECT 7, 'capacity:adjust', '选课容量调整', 'backend' FROM dual UNION ALL
    SELECT 8, 'log:view', '系统日志查看', 'backend' FROM dual UNION ALL
    SELECT 9, 'permission:view', '权限查看', 'backend' FROM dual
) src
ON (p.perm_id = src.perm_id)
WHEN NOT MATCHED THEN
    INSERT (perm_id, perm_code, perm_name, module)
    VALUES (src.perm_id, src.perm_code, src.perm_name, src.module);

MERGE INTO role_permission rp
USING (
    SELECT 2 AS role_id, perm_id FROM permission WHERE module = 'backend'
) src
ON (rp.role_id = src.role_id AND rp.perm_id = src.perm_id)
WHEN NOT MATCHED THEN
    INSERT (role_id, perm_id)
    VALUES (src.role_id, src.perm_id);

MERGE INTO "user" u
USING (
    SELECT 10000 AS user_id,
           'admin' AS username,
           '0192023a7bbd73250516f069df18b500' AS password,
           2 AS role_id,
           '系统管理员' AS real_name,
           1 AS status
      FROM dual
) src
ON (u.username = src.username)
WHEN NOT MATCHED THEN
    INSERT (user_id, username, password, role_id, real_name, status, create_time)
    VALUES (src.user_id, src.username, src.password, src.role_id, src.real_name, src.status, SYSDATE);

MERGE INTO administrator a
USING (
    SELECT 10000 AS user_id, 'ADM001' AS admin_no, 0 AS admin_level, '{"scope":"all"}' AS managed_scope FROM dual
) src
ON (a.user_id = src.user_id)
WHEN NOT MATCHED THEN
    INSERT (user_id, admin_no, admin_level, managed_scope)
    VALUES (src.user_id, src.admin_no, src.admin_level, src.managed_scope);

COMMIT;
