using System.IO.Compression;
using System.Text;
using System.Xml;
using StudentCourse.Models;
namespace StudentCourse.Services
{
    public sealed class EvaluationExportService
    {
        public byte[] BuildExcel(IList<AdminEvaluationDto> rows)
        {
            using MemoryStream stream=new(); using(ZipArchive zip=new(stream,ZipArchiveMode.Create,true)){ E(zip,"[Content_Types].xml","""<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>"""); E(zip,"_rels/.rels","""<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>"""); E(zip,"xl/workbook.xml","""<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="课程评价" sheetId="1" r:id="rId1"/></sheets></workbook>"""); E(zip,"xl/_rels/workbook.xml.rels","""<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>"""); E(zip,"xl/styles.xml","""<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><name val="Microsoft YaHei"/></font><font><b/><color rgb="FFFFFFFF"/><name val="Microsoft YaHei"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF3457D5"/></patternFill></fill></fills><borders count="2"><border/><border><left style="thin"/><right style="thin"/><top style="thin"/><bottom style="thin"/></border></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="2"><xf borderId="1"/><xf fontId="1" fillId="2" borderId="1" applyFill="1"/></cellXfs></styleSheet>"""); W(zip,rows);} return stream.ToArray();
        }
        private static void W(ZipArchive z,IList<AdminEvaluationDto> xs){using Stream s=z.CreateEntry("xl/worksheets/sheet1.xml").Open();using XmlWriter w=XmlWriter.Create(s,new XmlWriterSettings{Encoding=new UTF8Encoding(false)});const string n="http://schemas.openxmlformats.org/spreadsheetml/2006/main";w.WriteStartElement("worksheet",n);w.WriteStartElement("sheetViews",n);w.WriteStartElement("sheetView",n);w.WriteAttributeString("workbookViewId","0");w.WriteStartElement("pane",n);w.WriteAttributeString("ySplit","1");w.WriteAttributeString("state","frozen");w.WriteEndElement();w.WriteEndElement();w.WriteEndElement();w.WriteStartElement("sheetData",n);R(w,n,1,new[]{"学号","课程","教学班","教师","学期","教学设计","课堂讲授","教学互动","教学效果","综合评分","文字反馈","评价时间"},true);for(int i=0;i<xs.Count;i++){var x=xs[i];R(w,n,i+2,new[]{x.StudentNo,x.CourseName,x.ClassName,x.TeacherName,x.Semester,$"{x.D1Score}",$"{x.D2Score}",$"{x.D3Score}",$"{x.D4Score}",$"{x.EvalScore:0.0}",x.Comment,x.EvaluationTime},false);}w.WriteEndElement();w.WriteStartElement("autoFilter",n);w.WriteAttributeString("ref",$"A1:L{xs.Count+1}");w.WriteEndElement();w.WriteEndElement();}
        private static void R(XmlWriter w,string n,int r,IEnumerable<string?> vs,bool h){w.WriteStartElement("row",n);int c=0;foreach(var v in vs){w.WriteStartElement("c",n);w.WriteAttributeString("r",$"{(char)('A'+c++)}{r}");w.WriteAttributeString("t","inlineStr");w.WriteAttributeString("s",h?"1":"0");w.WriteStartElement("is",n);w.WriteElementString("t",n,v??"");w.WriteEndElement();w.WriteEndElement();}w.WriteEndElement();}
        private static void E(ZipArchive z,string p,string c){using StreamWriter w=new(z.CreateEntry(p).Open(),new UTF8Encoding(false));w.Write(c);}
    }
}
